version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt/certs:/etc/letsencrypt
      - ./letsencrypt/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem:ro

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: my-mongo-password  # Altere para uma senha mais segura
    networks:
      - app-network

  redis:
    image: redis:latest
    command: redis-server --requirepass my-redis-password  # Altere para uma senha mais segura
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/letsencrypt --agree-tos --no-eff-email --email andre@tos.world -d tos.world

networks:
  app-network:
    driver: bridge
